---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.10.9

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-8

suites:
  - name: default
    run_list:
      - recipe[nextcloud::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
